name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train_and_quantize:
    name: Train and Quantize Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python src/train.py

      - name: Run quantization script
        run: python src/quantize.py

  test_suite:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: train_and_quantize

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Re-run training to generate model
        run: python src/train.py

      - name: Run pytest
        run: pytest tests/

  build_and_test_container:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    needs: train_and_quantize

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t mlops-linear .

      - name: Run Docker Container and Test
        run: docker run mlops-linear

